PLUGIN_FOLDER?=/home/boris/.config/aseprite/extensions/lospec

compile:
	rm ./lospec.aseprite-extension
	zip -r lospec.aseprite-extension .

update:
	cp ./main.lua $(PLUGIN_FOLDER)/main.lua
	cp ./main.lua $(PLUGIN_FOLDER)/package.json
